const venues= [
  {
    "venueName": "LEELAVATI BANQUETS",
    "address": "P.O, 45th km Chennai - Mahabalipuram, ECR Road Krishnan Karnai, Pattipulam, Chennai, Tamil Nadu 603104, India",
    "phone": "+91 93848 01055",
    "email": "leelabanquets@gmail.com",
    "url": "http://www.leelavati.co.in/",
    "rating": 4.3,
    "seating": "200-300",
    "category_name": "Banquet halls",
    "price":20000
  },
  {
    "venueName": "Shrivaaru Venkataachalapathy Palace",
    "address": "Vanagaram-Ayanambakkam Road, 103, Poonamallee High Rd, Chennai, Tamil Nadu 600095, India",
    "phone": "+91 72990 49797",
    "email": "shrivaarupalace@gmail.com",
    "url": "https://shrivaarupalace.com/",
    "rating": 4.4,
    "seating": "1000-1500",
    "category_name": "Banquet halls",
    "price":30000
  },
  {
    "venueName": "Marriage Halls in Kovilambakkam",
    "address": "Veeramani Nagar, Kovilambakkam, Chennai, Tamil Nadu 600129, India",
    "phone": "+91 44 4991 6227",
    "email": "info.weddingz@oyorooms.com",
    "url": "https://weddingz.in/marriage-halls/chennai/kovilambakkam/?utm_source=Google_gmb&utm_medium=Organic&utm_campaign=LOC_Kovilambakkam",
    "rating": 4,
    "seating": "500-700",
    "category_name": "Banquet halls",
    "price":20000
  },
  {
    "venueName": "SS Grand Wedding Hall",
    "address": "Siluvathur Rd, Kalathu Kottam, Balakrishnapuram, Tamil Nadu 624005, India",
    "phone": "+91 98407 61927",
    "email": "ssgrandmahaldgl@gmail.com",
    "url": "https://ssgranddgl.com/",
    "rating": 5,
    "seating": "200",
    "category_name": "Banquet halls",
    "price": 30000
  },
  {
    "venueName": "The Blue House- Resorts In Ecr | Beach House In Ecr",
    "address": "No.10, 5th Drive Water Edge Lane, East Coast Rd, Sea Cliff Conclave, Akkarai, Chennai, Tamil Nadu 600119, India",
    "phone": "+91 63832 82186",
    "email": "bluehouseecr@gmail.com",
    "url": "http://thebluehouseecr.com/",
    "rating": 4.4,
    "seating": "500-700",
    "category_name": "Resort hotels",
    "price":50000
  },
  {
    "venueName": "Marriage Halls in Kolathur",
    "address": "Villivakkam, Kolathur, Chennai, Tamil Nadu 600082, India",
    "phone": "+91 44 4991 6227",
    "email":"kolathurhalls@gmail,com",
    "url": "https://weddingz.in/marriage-halls/chennai/kolathur/?utm_source=Google_gmb&utm_medium=Organic&utm_campaign=LOC_Kolathur",
    "rating": 5,
    "seating": "400-500",
    "category_name": "Banquet halls",
    "price":25000
  },
  {
    "venueName": "RR Mahal",
    "address": "85HM+CM8, Mookambigai Nagar, Ponneri, Tamil Nadu 601204, India",
    "phone": "+91 98408 08880",
    "email": "rrmahal2017@gmail.com",
    "url": "http://rrmahal.in/",
    "rating": 4.2,
    "seating": "200-300",
    "category_name": "Mandapam",
    "price":15000
  },
  {
    "venueName": "ஜி.கே.சித்ரா மகால் திருமண மண்டபம்",
    "address": "Madurai, Tamil Nadu 625012, India",
    "phone": "+91 94882 07000",
    "email": "care@mandap.com",
    "url": "http://gkchitramahal.matrimonymandapam.com/",
    "rating": 4.8,
    "seating": "200-300",
    "category_name": "Mandapam",
    "price":15000
  },
  {
    "venueName": "Blue Lagoon Wedding Complex",
    "address": "5/72, Raja Nagar, Neelankarai, Chennai, Tamil Nadu 600115, India",
    "phone": "+91 98840 27080",
    "email": "banquets@bluelagoonresorts.com",
    "url": "https://www.bluelagoonweddingcomplex.com/",
    "rating": 4.2,
    "seating": "200-300",
    "category_name": "Banquet halls",
    "price":35000
  },
  {
    "venueName": "Sri Balakashi Mahal",
    "address": "Om Aditya Nagar, Thekkalur, Tamil Nadu 641654, India",
    "phone": "+91 87548 60890",
    "email": "SriBalaKashi@gmail.com",
    "url": "http://sribalakashi.com/",
    "rating": 3.9,
    "seating": "300-400",
    "category_name": "Mandapam",
    "price":20000
  },
  {
    "venueName": "Gopinath Gardens",
    "address": "Injambakkam, Chennai, Tamil Nadu 600115, India",
    "phone": "+91 94449 41064",
    "email": "gopinathgardens@gmail.com",
    "url": "http://www.gopinathgardens.com/",
    "rating": 4.5,
    "seating": "900-1000",
    "category_name": "Outdoor Space",
    "price":70000
  },
  {
    "venueName": "SAN Event Hall",
    "address": "3/432, 4th Cross Street Lakshmana Perumal Nagar, Kottivakkam, Chennai, Tamil Nadu 600041, India",
    "phone": "+91 83001 61234",
    "email": "info@saneventhall.com",
    "url": "http://www.saneventhall.com/",
    "rating": 4.4,
    "seating": "700-800",
    "category_name": "Banquet halls",
    "price":25000
  },
  {
    "venueName": "Marriage Halls in Madipakkam",
    "address": "X57X+X8G, Balaiah Garden, Madipakkam, Chennai, Tamil Nadu 600091, India",
    "phone": "+91 44 4991 6227",
    "email": "info.weddingz@oyorooms.com",
    "url": "https://weddingz.in/marriage-halls/chennai/madipakkam/?utm_source=Google_gmb&utm_medium=Organic&utm_campaign=LOC_Madipakkam",
    "rating": 3,
    "seating": "100-200",
    "category_name": "Banquet halls",
    "price":15000
  },
  {
    "venueName": "Sri Rani Mahal",
    "address": "Major District Road 635, Veeramani Nagar, Keelkattalai, Chennai, Tamil Nadu 600091, India",
    "phone": "+91 98407 19993",
    "email": "sriranimahal0099@gmail.com",
    "url": "http://www.sriranimahal.com/",
    "rating": 4.3,
    "seating": "600-700",
    "category_name": "Mandapam",
    "price":30000
  },
  {
    "venueName": "Padma Nilayam Mini Hall A/C",
    "address": "11A/21, Tanjore Road, T. Nagar, Chennai, Tamil Nadu 600017, India",
    "phone": "+91 98844 20408",
    "email": "shreenilayamtnagar@gmail.com",
    "url": "http://www.padmanilayam.com/",
    "rating": 4.2,
    "seating": 100,
    "category_name": "Mini Hall",
    "price":10000
  },
  {
    "venueName": "JR Mahal A/C (Wedding, Event, Marriage Hall, Kalyana Mandabam Madurai)",
    "address": "Natham Rd, opposite E B Office, Tagore Nagar, Bharat Nagar, Tiruppalai, Madurai, Tamil Nadu 625014, India",
    "phone": "+91 76396 37020",
    "email": "jrmahalac@gmail.com",
    "url": "http://imartyellowpages.com/WEDDING-HALL-IN-MADURAI",
    "rating": 3.9,
    "seating": "200-300",
    "category_name": "Mandapam",
    "price":35000
  },
  {
    "venueName": "OCEAN PEARL MGM CONVENTION & WEDDING HALL - ECR - Chennai",
    "address": "1/74, East Coast Road, Muttukadu, MGM Beach Resorts, SH 49, Chennai, Tamil Nadu 603103, India",
    "phone": "+91 80 6906 5555",
    "email": "reservations@mgm-hotels.com",
    "url": "https://www.mgm-hotels.com/mgm-beach-resort-muthukadu-chennai/weddings-events/ocean-pearl.html",    "rating": 4.4,
    "seating": "100-200",
    "category_name": "Resort hotels",
    "price":50000
  },
  {
    "venueName": "YDK Mahal",
    "address": "Salem Main Road, opposite Podhigai Eng College, Tirupathur, Pallipattu, Tamil Nadu 635601, India",
    "phone": "+91 94433 22531",
    "email": "ydkmahal@gmail.com",
    "url": "http://www.ydkmahal.com/",
    "rating": 4.7,
    "seating": "400-500",
    "category_name": "Mandapam",
    "price":40000
  },
  {
    "venueName": "Sri GopiKrishna Kalyana Mandapam",
    "address": "Sholingur Rd, KRP Nagar, Arakkonam, Tamil Nadu 631003, India",
    "phone": "+91 97863 93039",
    "email": "bcanchi@gmail.com",
    "url": "https://sites.google.com/site/srigopikrishnakalyanamandapam/",
    "rating": 3.9,
    "seating": "500-600",
    "category_name": "Banquet halls",
    "price":45000
  },
  {
    "venueName": "CROWN PALACE A/C Wedding Hall CHENNAI",
    "address": "Plot.no 331/2A, Jayalakshmi Nagar, CROWN PALACE, Adhanur Main Rd, Urapakkam, Chennai, Tamil Nadu 603202, India",
    "phone": "+91 73050 80740",
    "email": "crownpalace.chennai@gmail.com",
    "url": "https://crownpalace.co.in/",
    "rating": 4.3,
    "seating": "300-400",
    "category_name": "Banquet halls",
    "price": 25000
  },
  {
    "venueName": "KK Thirumana Mahal",
    "address": "Bhuvaneshwari Nagar, Athur, Chengalpattu, to, Kanchipuram High road, Chengalpattu, Tamil Nadu 603101, India",
    "phone": "+91 94450 15656",
    "email": "kkmahalcgl@gmail.com",
    "url": "http://kkthirumanamahal.com/",
    "rating": 4.4,
    "seating": "600-700",
    "category_name": "Mandapam",
    "price":25000
  },
  {
    "venueName": "Muthu Mahal",
    "address": "Cheyur Road,Muthammal nagar, Pattarai, Avinashi, Tamil Nadu 641654, India",
    "phone": "+91 98430 51166",
    "email": "muthumahalerode@gmail.com",
    "url": "https://www.muthumahal.com/muthu-mahal-online-booking.php",
    "rating": 4.3,
    "seating": "400-500",
    "category_name": "Mandapam",
    "price":30000
  },
  {
    "venueName": "Ragam Mahal",
    "address": "MGFM+CWM, Arni-Cheyyar Rd, Cheyyar, Tamil Nadu 604407, India",
    "phone": "+91 95978 38681",
    "email": "noreply@blogger.com",
    "url": "http://ragamahal.blogspot.com/",
    "rating": 3.4,
    "seating": "300-400",
    "category_name": "Mandapam",
    "price":40000
  },
  {
    "venueName": "Grande Pavilion By Grande Bay Resort Mahabalipuram",
    "address": "East Coast Road, Salavankuppam, Mahabalipuram, Tamil Nadu 603104, India",
    "phone": "+91 44 4813 3853",
    "email": "sales@grandebayresort.in",
    "url": "https://www.grandebayresort.in/wedding-halls.php",
    "rating": 3.5,
    "seating": "100-200",
    "category_name": "Resort hotels",
    "price":45000
  },
  {
    "venueName": "DV White Palace",
    "address": "Vinayagapuram Bus Stand, Bus Stand, 1A, Perambur Red Hills High Rd, near Vinayagapuram, Sri Lakshmi Nagar, Thiru VI Ka Nagar, Madhavaram, Kadirvedu, Chennai, Tamil Nadu 600099, India",
    "phone": "+91 87545 33999",
    "email": "info@dvwhitepalace.com",
    "url": "http://www.dvwhitepalace.com/",
    "rating": 4.2,
    "seating": "900-1000",
    "category_name": "Banquet halls",
    "price":60000
  },
  {
    "venueName": "Marriage Halls in Palavakkam",
    "address": "Krishna Nagar, Palavakkam, Chennai, Tamil Nadu 600041, India",
    "phone": "+91 44 4991 6227",
    "email": "info.weddingz@oyorooms.com",
    "url": "https://weddingz.in/marriage-halls/chennai/palavakkam/?utm_source=Google_gmb&utm_medium=Organic&utm_campaign=LOC_Palavakkam",
    "rating": 0,
    "seating": 0,
    "zip": 600041,
    "primary_category_name": "Wedding venues",
    "category_name": "Banquet halls"
  },
  {
    "venueName": "Muthu Valli Paradise Ponneri",
    "address": "Thachur Koot Road State Highway 56 Thatchoor, Ponneri, Tamil Nadu 601101, India",
    "phone": "+91 99623 01234",
    "email": "muthuvalliparadise@gmail.com",
    "lat": 13.2960219,
    "lng": 80.1475672,
    "url": "https://www.muthuvalliparadise.com/",
    "rating": 4.2,
    "seating": "200-300",
    "category_name": "Resort hotels",
    "price":80000
  },
  {
    "venueName": "Eden Garden Event Hall(OMR)",
    "address": "217, Quide Millat Street, Navalur, Tamil Nadu 603103, India",
    "phone": "+91 91762 77897",
    "email": "seawaveparadise@gmail.com",
    "url": "http://edengardenhall.com/",
    "rating": 4.3,
    "seating": 36,
    "category_name": "Resort hotels",
    "price":100000
  },
  {
    "venueName": "Ramlakshmi Paradise",
    "address": "174, Grand Northern Trunk Rd, Ponniammanmedu, VS Mani Nagar, Madhavaram, Chennai, Tamil Nadu 600060, India",
    "phone": "+91 44 2553 0325",
    "email": "info@ramlakshmiparadise.com",
    "url": "http://ramlakshmiparadise.com/",
    "rating": 4.4,
    "seating": "1000-1500",
    "category_name": "Resort hotels",
    "price":100000
  },
  {
    "venueName": "Govind Mahal",
    "address": "MF83+CFR, 185, Gandhi Rd, Pandaladi, Mannargudi, Tamil Nadu 614001, India",
    "phone": "+91 90473 19850",
    "email": "dhanamhall@gmail.com",
    "url": "http://govindmahal.com/",
    "rating": 4.2,
    "seating": "100-200",
    "category_name": "Mandapam",
    "price":45000
  }
]

module.exports={venues}